export const projects = [
  {
    title: 'Book Store',
    description: "Academic project that I led. This simulates a perfectly functional e-book store with login, favorites, searchs, filters, cart, payment, also featuring a nice looking admin dashboard, ban/unban users, add/soft delete books",
    image: '/images/e-book-store.png',
    tags: ['Javascript', 'React JS', 'Node JS', 'Chakra UI'],
    source: 'https://github.com/mati-farias/E-commerce-BookStore',
    visit: 'https://e-commerce-book-store.vercel.app/',
    id: 1,
  },
  {
    title: 'Project Manager',
    description: "A complete project-manager app. You can create projects and tasks for those projects. You can assign them to different users and establish due-date for them",
    image: '/images/Dashboard-project-manager.png',
    tags: ['Tailwind', 'PHP', 'Laravel', 'Artisan', 'React JS', 'Node JS'],
    source: 'https://github.com/mati-farias/project-manager',
    visit: 'https://github.com/mati-farias/project-manager',
    id: 2,
  },
  {
    title: 'To-Do List',
    description: "I was in the need to organize my tasks, so I created this nice to do list. It works great, and after I deployed it just for myself, some friends asked if they could use it as well, so I decided to add a user logic using supabase",
    image: '/images/todo-list.png',
    tags: ['Javascript','React JS','Next JS', 'Node JS','Supabase'],
    source: 'https://github.com/mati-farias/todo-list-supabase',
    visit: 'https://todo-list-supabase-indol.vercel.app/',
    id: 3,
  },
  {
    title: 'Audio-Transcription app',
    description: "The Transcript App allows you to upload an audio file involving up to a two people conversation and receive a transcription of the audio in a convinient format. Upload your audio file (mp3, wav, etc.) and the app will return a beautifuly created chat. The app is built using the Gladia API, which is a powerful tool for speech recognition and transcription.",
    image: '/images/Transcript-app.png',
    tags: ['Javascript', 'React', 'Next Js', 'Rest API', 'Tailwind', 'Gladia API'],
    source: 'https://github.com/mati-farias/AudioTranscription-app',
    visit: 'https://audio-transcriptions-app.vercel.app/',
    id: 4,
  },
  {
    title: 'Cat Lover APP',
    description: "This is a fun app where you can find cute, funny pictures and gifs of cats! You can share the pic/gif with a share link and your friend will be able to see it.",
    image: '/images/CatLovers.png',
    tags: ['Javascript', 'React', 'Next Js', 'Rest API'],
    source: 'https://github.com/mati-farias/cat-lover-app',
    visit: 'https://cat-lover-app.vercel.app/',
    id: 5,
  },
  {
    title: 'Godot game',
    description: "This is just a simple game I made. It's a 2D platformer game with a lot of different levels and enemies. I used the Godot Engine to create the game and the Godot Game Engine to handle the game logic and physics. If you want to try it, reach out and I cand send you the source code or executable file!.",
    image: '/images/Godot-game.png',
    tags: ['Godot'],
    source: 'mailto:mati.farias1991@gmail.com',
    visit: 'mailto:mati.farias1991@gmail.com',
    id: 6,
  },
  
];

export const TimeLineData = [
  { year: 2019, text: 'Started my IT journey as a SAP consultant.', },
  { year: 2020, text: 'Switched from consultant to SAP developer (ABAP)', },
  { year: 2021, text: 'Moved to Europe, did a internship on MilkCrate.', },
  { year: 2022, text: 'Moved back to Argentina, Completed a Full-stack web developer bootcamp.', },
  { year: 2023, text: 'Expanded my knowledge and experience working for ALC-Media', },
  { year: 2024, text: 'Year in progress', },
];